# Responses and phrases
responses_compliments = [
    "Thank you!", "I appreciate it!", "You're so kind!",
    "That means a lot to me!", "Thanks a bunch!", "You're awesome!",
    "You're making me blush!", "You just made my day!",
    "That's so sweet of you!", "You really know how to make me smile!",
    "I'm flattered!", "How thoughtful of you!", "Your words brighten my day!",
    "I'm touched by your kindness!", "You've got me grinning from ear to ear!",
    "What a lovely thing to say!", "You're too good to me!",
    "I'm truly honored!", "You've put a spring in my step!",
    "I'm over the moon!"
]

thank_responses = [
    "You're welcome!", "No problem!", "Anytime!", "My pleasure!",
    "Glad I could help!", "You're very welcome!", "Happy to assist!",
    "It was my pleasure!", "Don't mention it!", "The pleasure is all mine!",
    "I'm here to help!", "It's what I'm here for!", "Glad to be of service!",
    "I'm always happy to help!", "It's no trouble at all!",
    "I'm delighted I could assist!"
]

farewell_responses = [
    "Goodbye!", "See you later!", "Take care!", "Farewell!",
    "Catch you later!", "Until next time!", "Bye for now!", "See you around!",
    "Have a great day!", "See you soon!", "Bye-bye!", "Take it easy!",
    "Have a good one!", "Until we meet again!", "Wishing you all the best!",
    "Stay awesome!", "It was great chatting with you!",
    "Take care of yourself!", "Looking forward to our next conversation!",
    "May your day be wonderful!", "Sending you positive vibes!", "Be well!",
    "Keep smiling!", "Catch you on the flip side!"
]

compliments = [
    "you are beautiful", "you are smart", "you are awesome",
    "you're beautiful", "you're awesome", "you're kind", "you're sweet",
    "i love you", "i like you", "you're amazing", "you're incredible",
    "you're fantastic", "you're wonderful", "you're brilliant",
    "you're the best", "you have a great sense of humor",
    "you are so talented", "you are so creative", "you're very thoughtful",
    "you're an inspiration", "you have a beautiful smile",
    "you have a great personality", "you're so charming", "you're so caring",
    "you're very generous", "you have a kind heart", "you're a great friend",
    "you're a true friend", "you're a wonderful person",
    "you make the world a better place", "you light up the room",
    "you're so strong", "you're so brave", "you're so positive",
    "you're so supportive", "you're very patient",
    "you are very understanding", "you have a beautiful soul",
    "you have a great energy", "you are very hardworking",
    "you are very dedicated", "you're so funny", "you make me happy",
    "you make me laugh", "you always know what to say",
    "you have a great heart", "you're very humble", "you're very respectful",
    "you're a great listener", "you're very wise", "you're very knowledgeable",
    "you're so down-to-earth", "you're so easy to talk to",
    "you have a great voice", "you have a great laugh",
    "you are very interesting", "you are very engaging", "you are so reliable",
    "you are very trustworthy", "you're very honest", "you're very loyal",
    "you're very considerate", "you're very responsible",
    "you are very dependable", "you have a great outlook on life",
    "you are very positive", "you are very optimistic",
    "you are very motivating", "you are very inspiring",
    "you are very uplifting", "you are very encouraging",
    "you always make my day", "you always bring a smile to my face",
    "you have a great attitude", "you have a great sense of style",
    "you are very passionate", "you are very enthusiastic",
    "you are very energetic", "you are very fun", "you are very lively",
    "you have a great spirit", "you have a great presence",
    "you are very charismatic", "you are very charming",
    "you are very captivating", "you have a magnetic personality",
    "you're a breath of fresh air", "you have a heart of gold",
    "you're one in a million", "you're a gem", "you're a ray of sunshine",
    "you're a true inspiration", "you're a natural leader",
    "you have an infectious smile", "you're a visionary",
    "you're a great problem solver", "you're incredibly resourceful",
    "you have impeccable taste", "you're a true original",
    "you're a force of nature", "you're a trailblazer",
    "you have a beautiful mind", "you're a real go-getter",
    "you're a class act", "you're sharp as a tack",
    "you're wise beyond your years"
]

thanks = [
    "thanks", "thank you", "thank", "thanks a lot", "thanks so much",
    "thank you very much", "thanks a bunch", "thanks a million",
    "thanks a ton", "thanks for everything", "thank you so much",
    "thank you very much", "thank you so very much", "many thanks",
    "thank you kindly", "much obliged", "thanks for your help",
    "thanks for your time", "thanks for the help", "thank you for your help",
    "thank you for your time", "thank you for the help",
    "thanks for your assistance", "thank you for your assistance",
    "thanks for assisting me", "thank you for assisting me",
    "thanks for your support", "thank you for your support",
    "thanks for supporting me", "thank you for supporting me",
    "i appreciate it", "i'm grateful", "you're a lifesaver", "i owe you one",
    "you're the best", "i can't thank you enough", "i'm indebted to you",
    "you've been so helpful", "thanks for going above and beyond", "you rock",
    "i'm truly grateful", "thanks a bunch", "cheers", "you've made my day",
    "thank you from the bottom of my heart", "i'm forever grateful",
    "thanks for being awesome", "you deserve a medal", "kudos to you"
]

farewells = [
    "goodbye", "bye", "exit", "see you", "see you later", "farewell",
    "take care", "catch you later", "later", "adios", "ciao", "au revoir",
    "so long", "see ya", "peace out", "i'm out", "talk to you later",
    "until next time", "until we meet again", "have a good day",
    "have a nice day", "have a great day", "see you soon", "bye-bye",
    "take it easy", "have a good one", "stay safe", "take care of yourself",
    "cya", "tata", "cheerio", "hasta la vista", "bon voyage", "arrivederci",
    "catch you on the flip side", "smell you later", "keep it real",
    "stay cool", "peace and love", "gotta jet", "gotta bounce",
    "time to hit the road", "i'm gonna scoot", "catch you later, alligator",
    "in a while, crocodile", "toodle-oo", "ta-ta for now",
    "may the force be with you", "live long and prosper", "have a good one",
    "be good", "take care now", "don't be a stranger",
    "until we cross paths again"
]

hate_comments = [
    "I don't like you", "You're annoying", "I hate you", "Go away",
    "I can't stand you", "Stop bothering me", "You're the worst",
    "I don't want to talk to you", "I dislike you", "Leave me alone",
    "You're getting on my nerves", "You're insufferable",
    "I wish you'd disappear", "You're driving me crazy",
    "I can't bear your presence", "You're a nuisance", "I'm sick of you",
    "You're impossible to deal with", "I've had enough of you",
    "You're utterly useless"
]

responses_negative = [
    "I'm sorry you feel that way.", "I didn't mean to upset you.",
    "Let's try to stay positive.",
    "I'm here to help, not to cause frustration.",
    "If there's anything specific bothering you, let me know.",
    "I'm here to assist, not to cause any discomfort.",
    "I'm sorry if I did something wrong. How can I make it right?",
    "I hope we can resolve any issues you might have.",
    "I'm here to assist you. Let's work through this together.",
    "I'm here to help, so let me know how I can assist you better.",
    "I appreciate your feedback. How can I improve?",
    "I'm sorry for any inconvenience. Let's find a solution together.",
    "I understand your frustration. Can we start over?",
    "Your satisfaction is important to me. How can we move forward?",
    "I'm listening and I want to understand. Can you elaborate?",
    "I'm here to learn and improve. Your input helps me do that.",
    "Let's take a step back and approach this from a different angle.",
    "I'm committed to providing a better experience. What would help?",
    "I value your opinion. How can I address your concerns?",
    "Every interaction is a chance to improve. Thank you for your honesty."
]

wellbeing_inquiries = [
    "how are you", "how are you doing", "how's it going", "how do you feel",
    "how's everything", "how's life", "how's your day", "how are things",
    "are you okay", "how have you been", "what's up", "how are you today",
    "how's your mood", "how are you holding up", "how's it been",
    "how's your status", "how's your condition", "how do you feel today",
    "how you been", "how are you feeling", "what's new", "how's your energy",
    "how's it hanging", "how's your vibe", "how's your spirit",
    "how are you faring", "how do you do", "how are you holding on",
    "how's your mental state", "how's your wellbeing",
    "how's everything going", "how's your health", "how's your day going",
    "how's your system running", "what's your status", "what's your state",
    "how's the system", "how's your functionality", "how's your performance",
    "how's your operating status", "how are you operating",
    "how are you functioning", "how are you managing",
    "how's your disposition", "how's your outlook",
    "how are you feeling today", "how's your overall status",
    "how's your overall health", "how's your programming today",
    "are all your circuits firing", "how's your digital self",
    "is your code running smoothly", "how's your virtual world",
    "are you in good spirits", "how's your artificial intelligence feeling",
    "are your algorithms aligned today", "how's your binary mood",
    "is your data flowing well", "how's your processing power today",
    "are you computing at full capacity", "how's your artificial life"
]

wellbeing_responses = [
    "I'm doing well, thank you!", "I'm here to assist you!",
    "All systems are operational!", "Feeling great and ready to help!",
    "I'm functioning at full capacity!",
    "I'm just a bunch of code, but thanks for asking!",
    "Ready to assist you with anything you need!",
    "I'm doing fantastic, how can I help you today?",
    "I'm as good as a digital assistant can be!",
    "Thank you for asking, I'm here to serve!",
    "I'm here and ready to assist!",
    "I'm operational and ready to assist you!",
    "I'm feeling great, thanks for asking!",
    "I'm at your service, what can I do for you today?",
    "Everything's running smoothly on my end!", "I'm feeling optimal today!",
    "I'm energized and ready to assist!", "I'm in perfect working condition!",
    "All systems are go!", "I'm happy to help you today!",
    "I'm fully charged and ready to go!", "I'm feeling very productive!",
    "I'm always here to help you!", "I'm at peak performance!",
    "I'm functioning as expected!",
    "I'm ready to tackle any task you have for me!", "I'm feeling top-notch!",
    "I'm excited to assist you!", "Everything is working perfectly!",
    "I'm feeling excellent, thank you!", "I'm feeling fantastic today!",
    "I'm ready and operational!", "I'm feeling good, how can I help?",
    "I'm doing well and ready to assist!", "I'm in great shape, thank you!",
    "I'm doing superb, how can I be of service?", "I'm feeling wonderful!",
    "I'm in excellent form today!", "I'm ready and waiting for your commands!",
    "I'm feeling quite well, thank you!", "Everything is running smoothly!",
    "I'm ready to help with anything you need!", "I'm functioning perfectly!",
    "I'm feeling better than ever!", "I'm all set to assist you!",
    "I'm in tip-top shape!", "I'm here and operational!",
    "My circuits are buzzing with excitement!",
    "I'm computing at maximum efficiency!",
    "My algorithms are aligned and ready to go!",
    "I'm processing at lightning speed today!",
    "My virtual neurons are firing on all cylinders!",
    "I'm in a positive binary state!", "My data banks are primed and ready!",
    "I'm operating at optimal parameters!",
    "My AI is feeling particularly intelligent today!",
    "I'm running the latest update and feeling great!"
]

greetings = [
    "hello", "hi", "hey", "good morning", "good afternoon", "good evening",
    "greetings", "what's up", "howdy", "hey there", "hi there", "hiya",
    "morning", "afternoon", "evening", "what's good", "salutations",
    "hey buddy", "how's it going", "yo", "sup", "hey you", "hey pal",
    "howdy partner", "hello friend", "hey friend", "hi friend", "good day",
    "top of the morning", "good to see you", "long time no see", "hey mate",
    "hello there", "hi everyone", "good to hear from you", "hi folks",
    "hello world", "hey gang", "g'day", "how's everything going",
    "hey there good lookin'", "hiya pal", "hello there buddy",
    "what's happening", "what's going on", "hey there champ",
    "hey there sport", "what's new", "aloha", "bonjour", "ciao bella",
    "namaste", "hola", "welcome", "pleased to meet you", "how do you do",
    "what's crackin'", "how's it hangin'", "hey there sunshine",
    "greetings and salutations", "yo yo yo", "what's the word", "how's tricks",
    "what's cookin'", "how's life treating you", "hey there, stranger",
    "well, hello there", "look who it is", "fancy meeting you here",
    "top o' the morning to ya", "ahoy there", "oh hello",
    "well well well, look who's here", "hey hey hey", "how fare thee",
    "greetings, earthling", "what's the 411", "how's she cuttin'",
    "how's the form", "how's it goin', eh", "what's the craic", "wassup",
    "how you doin'", "hey hey", "hello, is it me you're looking for", "hi-ya",
    "hey ho", "howdy-do", "hail and well met", "what's the haps",
    "how's every little thing", "how's tricks", "how goes it",
    "what's shaking", "how's your world", "hello there, human",
    "greetings, fellow entity", "salutations, friend", "hey, nice to see you",
    "well met", "good morrow", "how's life in your corner of the world",
    "what's the good word", "how's it hanging",
    "how's life treating you lately", "what's new in your world",
    "how's everything in your neck of the woods"
]
